name: Generate Trophy

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari jam 00:00 UTC
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ivan-4k
          file: assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update trophy svg"
          file_pattern: assets/trophy.svg
